### ISSUE TITLE
Build fails: thread 'main' panicked

### ISSUE THREAD

**Issue by yurivict** [Polochon-street/bliss-rs#60]
```
   Compiling aho-corasick v0.7.20
     Running `CARGO=/usr/local/bin/cargo CARGO_CRATE_NAME=aho_corasick CARGO_MANIFEST_DIR=/usr/ports/audio/bliss-rs/work/bliss-rs-97f563d/cargo-crates/aho-corasick-0.7.20 CARGO_PKG_AUTHORS='Andrew Gallant <jamslam@gmail.com>' CARGO_PKG_DESCRIPTION='Fast multiple substring searching.' CARGO_PKG_HOMEPAGE='https://github.com/BurntSushi/aho-corasick' CARGO_PKG_LICENSE='Unlicense OR MIT' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=aho-corasick CARGO_PKG_REPOSITORY='https://github.com/BurntSushi/aho-corasick' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.7.20 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=7 CARGO_PKG_VERSION_PATCH=20 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/usr/ports/audio/bliss-rs/work/target/release/deps:/usr/local/lib' /usr/local/bin/rustc --crate-name aho_corasick --edition=2018 /usr/ports/audio/bliss-rs/work/bliss-rs-97f563d/cargo-crates/aho-corasick-0.7.20/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -C panic=abort -C linker-plugin-lto -C codegen-units=1 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=da22d7a0a07769e7 -C extra-filename=-da22d7a0a07769e7 --out-dir /usr/ports/audio/bliss-rs/work/target/x86_64-unknown-freebsd/release/deps --target x86_64-unknown-freebsd -C linker=cc -L dependency=/usr/ports/audio/bliss-rs/work/target/x86_64-unknown-freebsd/release/deps -L dependency=/usr/ports/audio/bliss-rs/work/target/release/deps --extern memchr=/usr/ports/audio/bliss-rs/work/target/x86_64-unknown-freebsd/release/deps/libmemchr-593d96310239a278.rmeta --cap-lints warn -C link-arg=-fstack-protector-strong`
     Running `/usr/ports/audio/bliss-rs/work/target/release/build/bliss-audio-aubio-sys-a37581d54bd9744c/build-script-build`
[bliss-audio-aubio-sys 0.2.0] thread 'main' panicked at 'No prebuilt bindings. Try use `bindgen` feature.', /usr/ports/audio/bliss-rs/work/bliss-rs-97f563d/cargo-crates/bliss-audio-aubio-sys-0.2.0/build.rs:34:13
[bliss-audio-aubio-sys 0.2.0] stack backtrace:
[bliss-audio-aubio-sys 0.2.0]    0: std::panicking::begin_panic
[bliss-audio-aubio-sys 0.2.0]    1: build_script_build::main
[bliss-audio-aubio-sys 0.2.0]    2: core::ops::function::FnOnce::call_once
[bliss-audio-aubio-sys 0.2.0] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `bliss-audio-aubio-sys v0.2.0`

Caused by:
  process didn't exit successfully: `/usr/ports/audio/bliss-rs/work/target/release/build/bliss-audio-aubio-sys-a37581d54bd9744c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'No prebuilt bindings. Try use `bindgen` feature.', /usr/ports/audio/bliss-rs/work/bliss-rs-97f563d/cargo-crates/bliss-audio-aubio-sys-0.2.0/build.rs:34:13
  stack backtrace:
     0: std::panicking::begin_panic
     1: build_script_build::main
     2: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
warning: `bindgen` (lib) generated 3 warnings
*** Error code 101
```

rust-1.67.1
FreeBSD 13.1

**Comment by Polochon-street** [comment]
Hi,

What did you run to try and build it? `cargo build`?
What happens if you try `cargo build --features=default,bliss-audio-aubio-rs/bindgen`?

**Comment by yurivict** [comment]
> What did you run to try and build it? cargo build?

cargo build


> What happens if you try cargo build --features=default,bliss-audio-aubio-rs/bindgen?

Then it fails with this message:
```
===>  Building for bliss-rs-g20230316
error: failed to select a version for the requirement `bindgen = "^0.58"`
candidate versions found which didn't match: 0.64.0
location searched: directory source `/wrkdirs/usr/ports/audio/bliss-rs/work/bliss-rs-743f779/cargo-crates` (which is replacing registry `crates-io`)
required by package `bliss-audio-aubio-sys v0.2.0`
    ... which satisfies dependency `bliss-audio-aubio-sys = "^0.2.0"` (locked to 0.2.0) of package `bliss-audio-aubio-rs v0.2.0`
    ... which satisfies dependency `bliss-audio-aubio-rs = "^0.2.0"` (locked to 0.2.0) of package `bliss-audio v0.6.7 (/wrkdirs/usr/ports/audio/bliss-rs/work/bliss-rs-743f779)`
perhaps a crate was updated and forgotten to be re-vendored?
*** Error code 101 
```

**Comment by yurivict** [comment]
With ```--features=default,bliss-audio-aubio-rs/bindgen``` it strangely begins to depend on multiple versions of bindgen.

**Comment by Polochon-street** [comment]
hmm, could you try again with bliss-rs 0.6.7? I just bumped it and some other deps with the latest version of bindgen - maybe that will solve your problem

**Comment by lukasroberts** [comment]
I also encounter the same error using bliss-rs 0.6.7. alongside rust 1.67.1 (d5a82bbd2 2023-02-07) on a MacBook Pro (m1)

**Comment by Polochon-street** [comment]
Could you post the output of both `cargo build --features=default,bliss-audio-aubio-rs/bindgen` and `cargo build`?

**Comment by lukasroberts** [comment]
For `cargo build --features=default,bliss-audio-aubio-rs/bindgen`

I get - `error: none of the selected packages contains these features: bliss-audio-aubio-rs/bindgen, default`

For cargo build

I get - 

```
error: failed to run custom build command for `bliss-audio-aubio-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/Users/x/Documents/Github/Cutz/cutz/target/debug/build/bliss-audio-aubio-sys-879693fa372e2dc3/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'No prebuilt bindings. Try use `bindgen` feature.', /Users/x/.cargo/registry/src/github.com-1ecc6299db9ec823/bliss-audio-aubio-sys-0.2.1/build.rs:34:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Looks like it's related to [audio](https://crates.io/crates/aubio/0.2.1) because when I try to build that I get the exact same error.

**Comment by Polochon-street** [comment]
Alright, the bindgen thing is because I'm not exposing the feature on bliss-rs.
Let's try to see if you can build aubio first - what happens if you do
`git clone --recursive "git@github.com:Polochon-street/aubio-rs.git"` (it's an optimized version of aubio for the bliss use case), then in `aubio-rs`, `cargo build --features=bindgen`?

If this work I think just adding the feature to `bliss-rs` would work

**Comment by lukasroberts** [comment]
That unfortunately failed with the following:

error: failed to run custom build command for `bliss-audio-aubio-sys v0.2.1 (/Users/lukasroberts/Downloads/aubio-rs-318bc5dffc29f7ac96d6b3ab082936915c973cfb/bliss-audio-aubio-sys)`

```
Caused by:
  process didn't exit successfully: `/Users/x/aubio-rs-318bc5dffc29f7ac96d6b3ab082936915c973cfb/target/debug/build/bliss-audio-aubio-sys-1b8839b3dae3f98a/build-script-build` (exit status: 101)
  --- stderr
  /Users/x/aubio-rs-318bc5dffc29f7ac96d6b3ab082936915c973cfb/bliss-audio-aubio-sys/library.h:1:10: fatal error: 'aubio.h' file not found
  thread 'main' panicked at 'Generated bindings.: ClangDiagnostic("/Users/x/aubio-rs-318bc5dffc29f7ac96d6b3ab082936915c973cfb/bliss-audio-aubio-sys/library.h:1:10: fatal error: 'aubio.h' file not found\n")', bliss-audio-aubio-sys/build.rs:90:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lukasroberts** [comment]
Running `cargo build --features=bindgen` does indeed work!

**Comment by Polochon-street** [comment]
awesome! Just made this PR https://github.com/Polochon-street/bliss-rs/pull/62, could you check that the corresponding branch allows you to compile everything correctly? (`add-bindgen-feature`)

`cargo build --features=update-aubio-bindings` from that branch should do the trick :crossed_fingers: 

If everything works, I'll push a new bliss-rs version to crates.io :)

**Comment by lukasroberts** [comment]
Just switched onto that branch, ran that command and it builds - awesome stuff. Thank you very much!

**Comment by Polochon-street** [comment]
awesome, thanks for confirming :)

@yurivict, does `cargo build --features=update-aubio-bindings` work for you with bliss-rs 0.6.8?

**Comment by lukasroberts** [comment]
@Polochon-street just tried to `cargo build` with 0.6.8 and am getting the following error:

```
error: failed to run custom build command for `bliss-audio-aubio-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/Users/x/target/debug/build/bliss-audio-aubio-sys-0e47044f462d1d40/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'No prebuilt bindings. Try use `bindgen` feature.', /Users/x/.cargo/registry/src/github.com-1ecc6299db9ec823/bliss-audio-aubio-sys-0.2.1/build.rs:34:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Polochon-street** [comment]
You can also add a `default` feature in Cargo.toml with this I think, to just be able to type `cargo build` and be done with it:
```
[features]
default = ["bliss-audio/update-aubio-bindings"]
```

**Comment by yurivict** [comment]
Current revision still fails with features=default:
```
     Running `/usr/ports/audio/bliss-rs/work/target/release/build/bliss-audio-aubio-sys-2b0d5d687a5a52ae/build-script-build`
[bliss-audio-aubio-sys 0.2.1] thread 'main' panicked at 'No prebuilt bindings. Try use `bindgen` feature.', /usr/ports/audio/bliss-rs/work/bliss-rs-9ddadb4/cargo-crates/bliss-audio-aubio-sys-0.2.1/build.rs:34:13
[bliss-audio-aubio-sys 0.2.1] stack backtrace:
[bliss-audio-aubio-sys 0.2.1]    0: std::panicking::begin_panic
[bliss-audio-aubio-sys 0.2.1]    1: build_script_build::main
[bliss-audio-aubio-sys 0.2.1]    2: core::ops::function::FnOnce::call_once
[bliss-audio-aubio-sys 0.2.1] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `bliss-audio-aubio-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/usr/ports/audio/bliss-rs/work/target/release/build/bliss-audio-aubio-sys-2b0d5d687a5a52ae/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'No prebuilt bindings. Try use `bindgen` feature.', /usr/ports/audio/bliss-rs/work/bliss-rs-9ddadb4/cargo-crates/bliss-audio-aubio-sys-0.2.1/build.rs:34:13
  stack backtrace:
     0: std::panicking::begin_panic
     1: build_script_build::main
     2: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
warning: `matrixmultiply` (lib) generated 4 warnings
```

rust-1.68.0
FreeBSD 13.1

**Comment by yurivict** [comment]
... but with ```features=default,bliss-audio-aubio-rs/bindgen``` it passes this point.

**Comment by Polochon-street** [comment]
hi @yurivict ! I'm wondering, is this issue solved? Or did it fail again down the line?

**Comment by Polochon-street** [comment]
Hi @yurivict, ffmpeg-next got bumped with a fix for FreeBSD, I tested on a VM, and things seem to work. Do you confirm on your end? :)

**Comment by Polochon-street** [comment]
closing this since it's been some time since last activity - feel free to reopen if needed.
